/* tslint:disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Media {
  id: string
  alt: string
  url?: string
  filename?: string
  mimeType?: string
  filesize?: number
  width?: number
  height?: number
  createdAt: string
  updatedAt: string
}

export interface Post {
  id: string
  title: string
  slug: string
  description: string
  publicationDate: string
  featuredImage?: string | Media
  tags?:
    | (
        | 'React'
        | 'JavaScript'
        | 'TypeScript'
        | 'Frontend'
        | 'Backend'
        | 'Python'
        | 'DevOps'
        | 'Testing'
        | 'Architecture'
        | 'Performance'
        | 'TDD'
        | 'Next.js'
        | 'Node.js'
        | 'CSS'
        | 'Database'
      )[]
    | null
  canonicalUrl?: string
  content: unknown
  updatedAt: string
  createdAt: string
  _status?: 'draft' | 'published'
}

export interface User {
  id: string
  name?: string
  email: string
  password: string
  createdAt: string
  updatedAt: string
}
