name: 'Setup Playwright'
description: 'Setup Playwright with caching and install browsers with dependencies'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js and pnpm
      uses: ./.github/actions/setup-node-pnpm

    - name: Store Playwright's Version
      run: |
        PLAYWRIGHT_VERSION=$(pnpm list @playwright/test --depth=0 | grep @playwright | sed 's/.*@//')
        echo "Playwright's Version: $PLAYWRIGHT_VERSION"
        echo "PLAYWRIGHT_VERSION=$PLAYWRIGHT_VERSION" >> $GITHUB_ENV
      shell: bash

    - name: Cache Playwright Browsers for Playwright's Version
      id: cache-playwright-browsers
      uses: actions/cache@v4
      with:
        path: ~/.cache/ms-playwright
        key: portfolio-playwright-browsers-${{ env.PLAYWRIGHT_VERSION }}

    - name: Setup Playwright
      if: steps.cache-playwright-browsers.outputs.cache-hit != 'true'
      run: pnpm playwright install --with-deps
      shell: bash

    - name: Install system dependencies for Playwright
      run: pnpm playwright install-deps
      shell: bash
