name: Update Visual Snapshots

on:
  workflow_dispatch: # Manual trigger

permissions:
  contents: write

jobs:
  update-snapshots:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Playwright
        uses: ./.github/actions/setup-playwright

      - name: Update visual snapshots
        run: pnpm test:integration --grep "visual regression" --update-snapshots

      - name: Upload generated snapshots as artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: updated-visual-snapshots
          path: integration-tests/
          retention-days: 30

      - name: Commit updated snapshots
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if git diff --staged --quiet; then
            echo "No snapshot changes to commit"
          else
            git commit -m "chore: update visual regression snapshots"
            git push
          fi
