name: Update Visual Snapshots

on:
  workflow_dispatch: # Manual trigger

permissions:
  contents: write

jobs:
  update-snapshots:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js and pnpm
        uses: ./.github/actions/setup-node-pnpm

      - name: Store Playwright's Version
        run: |
          PLAYWRIGHT_VERSION=$(pnpm list @playwright/test --depth=0 | grep @playwright | sed 's/.*@//')
          echo "Playwright's Version: $PLAYWRIGHT_VERSION"
          echo "PLAYWRIGHT_VERSION=$PLAYWRIGHT_VERSION" >> $GITHUB_ENV

      - name: Cache Playwright Browsers for Playwright's Version
        id: cache-playwright-browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: portfolio-playwright-browsers-${{ env.PLAYWRIGHT_VERSION }}

      - name: Setup Playwright
        if: steps.cache-playwright-browsers.outputs.cache-hit != 'true'
        run: pnpm playwright install --with-deps

      - name: Install system dependencies for Playwright
        run: pnpm playwright install-deps

      - name: Update snapshots
        run: pnpm test:integration --update-snapshots

      - name: Upload generated snapshots as artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: updated-visual-snapshots
          path: integration-tests/
          retention-days: 30

      - name: Commit updated snapshots
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if git diff --staged --quiet; then
            echo "No snapshot changes to commit"
          else
            git commit -m "chore: update visual regression snapshots [skip ci]"
            git push
          fi
